services:
    net-mon:
        container_name: net-mon
        image: ghcr.io/rafhaanshah/net-mon:latest
        restart: unless-stopped
        network_mode: host # needed for nmap to get mac addresses
        volumes:
          - ./results.json:/app/results.json # optional, if you want to keep found hosts persistent.
                                             # create an empty results.json first
        environment:
          - NETMON_NOTIFICATION=tgram://bottoken/ChatID
          - NETMON_SUBNET=192.168.1.0/24
          - NETMON_MINUTES=60
